### ISSUE TITLE
extracting content, salience, novelty etc.

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#10]
hi @hpzhao, do you know how one might extract the computed features from this model such as `content`, `salience`, `novelty`, `abs. pos. imp`, `rel. pos. imp`?

<img width="789" alt="screen shot 2018-02-27 at 9 49 30 pm" src="https://user-images.githubusercontent.com/2790092/36767375-3e7d0d74-1c08-11e8-9eed-606a030ea040.png">

**Comment by hpzhao** [comment]
Sorry,I don't figure it out  what you mean. You mean how to get the values from my model?

**Comment by AlJohri** [comment]
Yup!

**Comment by hpzhao** [comment]
You could just print their value in model.py

2018-02-28 18:25 GMT+08:00 Al Johri <notifications@github.com>:
