### ISSUE TITLE
Final performances ?

### ISSUE THREAD

**Issue by diegoantognini** [hpzhao/SummaRuNNer#11]
Hi,

I was wondering what was the final performances of the model. Can it reproduce more or less the reported results ?

Thank you for your help !

**Comment by hpzhao** [comment]
I get similar ROUGE scores with the paper. The position features may differ from the paper because the author didn't put it clearly in the paper. I'll optimize the code in a few days. Thanks for your attention. @Diego999

**Comment by diegoantognini** [comment]
Thanks for the answer @hpzhao , my model is still training since yesterday (epoch 4 now) Do you have a number ?. Yes I observed the position embeddings are different. And I also find ambiguous how they quantized segment in document. However I don't see neither summary embeddings.

**Comment by hpzhao** [comment]
4-5 epochs. In my experiment, I utilized 10 embeddings to represent the segment. The rel index is int((cur_index / total_length) * 10).@Diego999

**Comment by AlJohri** [comment]
here's a sample trained model at 5 epochs: https://files.fm/u/h22emf2j
