### ISSUE TITLE
word2id file?

### ISSUE THREAD

**Issue by jiangix01** [hpzhao/SummaRuNNer#12]
Hi, hpzhao:
   Very sorry for bothering you. I want to know how can i get the word2id file. What is the start id number? And may i need to remove some words when generating word2id? Can you provide me a vocabulary table including words need to remove? 
   Thanks a lot.

**Comment by hpzhao** [comment]
@jiangix01 Hi, there is word2id file in my released data. Firstly, I utilized word2vec to train word embedding s with the corpus. And the word min count is set to 5.  Then I generate the word2id from the embeddings. The first token is PAD, the second is UNK. I hope it will help you.

**Comment by jiangix01** [comment]
Yep, It helps me a lot. Thank you very much again.

**Comment by AlJohri** [comment]
Here is the word2id file as a json:

```
curl "https://gist.githubusercontent.com/AlJohri/16712bdf7b10dea65b5d95b7a61fa4b9/raw/007931bec71e5ae3acbfad87d333adc7fbf23246/word2id.json"
```
