### ISSUE TITLE
NLP-OSS conf

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#13]
hey @hpzhao, if you want, you could convert this into an installable package and perhaps submit to this conf: https://nlposs.github.io/

![screen shot 2018-03-08 at 6 16 06 pm](https://user-images.githubusercontent.com/2790092/37181879-cb907c8c-22fc-11e8-8f75-eda558ed3518.png)

maybe something about productionizing / distributing pytorch models? issues with going from paper -> code, what kinds of things should authors include to make it easier to code etc.

**Comment by hpzhao** [comment]
Thanks for your information. I just rewritten the code. But I don't have the plan to convert this into an installable package for the time being. I'll think about it. Anyway, thanks for your advice. @AlJohri
