### ISSUE TITLE
One GRU network for a mini batch, i.e. multiple documents

### ISSUE THREAD

**Issue by htamori** [hpzhao/SummaRuNNer#15]
Hi,
I'm wondering why your forward network has only one word and sentence level GRUs. I understand that these GRUs need to be executed for each document, but I guess your GRUs are executed at once for whole documents in a mini batch.

Thank you for your help!

**Comment by hpzhao** [comment]
The two GRUs are used for modeling sentences and documents. Different sentences or docs share the same functional module(GRU). So I don't think it's necessary to add more GRUs. @htamori

**Comment by htamori** [comment]
@hpzhao Got it. Thanks a lot!
