### ISSUE TITLE
provide data as non-pickle files?

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#18]
hi @hpzhao, is there any chance you can make the data as gzipped [line json](http://jsonlines.org/examples/) or text files? the binary pickle files are a bit less portable. for example, I'm trying to run the code using Python 3 instead of Python 2 and run into issues with the pickle files.

in addition, the pickle files are deeply tied to your utility classes instead of raw numpy objects, torch tensors, or dicts etc. if one tries to unpickle the file from the wrong location, it will complain and say `utils.Dataset` or `utils.Vocab` not found.

you can load the raw data from the line json and then initialize the Vocab or Dataset class after loading the raw data.

as a side benefit I found the file sizes to be much smaller as well. in my personal fork based on the old code, I could fit these files into the repo itself:

![screen shot 2018-04-04 at 5 24 07 pm](https://user-images.githubusercontent.com/2790092/38335655-0ff46b64-382d-11e8-8a08-b88d4891e97e.png)

I used the [npz (numpy compressed)](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savez_compressed.html) format for the embedding which brought the file size down to 66mb.

i'd be happy to do this and submit as a PR if you're interest, please let me know!

**Comment by hpzhao** [comment]
Thanks for your advice. Your solution is better for different environment. I'm appreciated it if you can change the code and provide the data. @AlJohri
