### ISSUE TITLE
question about vocab.make_features

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#23]
hey @hpzhao, I'm a little confused about how the `vocab.make_features` method works. I'm trying to write an individual document predict method.

It looks like `sents_list` combines sentences across the batch of documents and feeds it to the `net` at once? Is this different from how it previously worked? how does the net know when one document ends and the next begins? I remember seeing this old `prepare_data` method which made me thing it was going one document at a time:

```python
def prepare_data(doc, word2id):
    data = deepcopy(doc.content)
    max_len = -1
    for sent in data:
        words = sent.strip().split()
        max_len = max(max_len, len(words))
    sent_list = []
     
    for sent in data:
        words = sent.strip().split()
        sent = [word2id[word] if word in word2id else 1 for word in words]
        sent += [0 for _ in range(max_len - len(sent))]
        sent_list.append(sent)
    
    sent_array = numpy.array(sent_list)
    label_array = numpy.array(doc.label)

    return sent_array, label_array
```

Thanks!

**Comment by hpzhao** [comment]
`doc_len`  is calculated in `vocab.make_features()` , so I can infer the `start index` and `end index` of each document in a batch. If you wanna predict a doc, just set `batch_size=1`. Or I'll complete the `predict()` in `main.py` @AlJohri
