### ISSUE TITLE
abstractive training?

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#24]
hey @hpzhao, have you tried implementing the abstractive training mode? I'm a _little_ suspicious of some of the sentence labels based on spot checking the data

**Comment by hpzhao** [comment]
Not yet. The abs training mode did't achieve SOTA. In my analysis, the dataset is not perfect but quite reasonable. I suggest you can jump out the dataset and SummaRuNNer. @AlJohri

**Comment by AlJohri** [comment]
Cool thanks. What do you mean “jump out”?

**Comment by hpzhao** [comment]
I mean you could build your own dataset and design your own network. I'm working on it.

**Comment by AlJohri** [comment]
Yep, I'm working on building my own dataset right now- but its attractive summaries
