### ISSUE TITLE
how many epochs should be trained? and how to get the ROUGE score?

### ISSUE THREAD

**Issue by iriscxy** [hpzhao/SummaRuNNer#25]

**Comment by hpzhao** [comment]
hi, @yingtaomj . In my experiments, you could achieve SOTA in 5 epochs. 
To get ROUGE SCORE, you should install [ROUGE-1.5.5](https://github.com/hpzhao/nlp-metrics) and `pyrouge`. Then you could get the ROUGE SCORE by `eval.py` in `outputs/` dir.
