### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by mollynatsu** [hpzhao/SummaRuNNer#26]
Do you have a copy of a pre-trained model that could be used to extract key sentences from other text?

**Comment by AlJohri** [comment]
@hpzhao if you're interested, you can distribute a pretrained model with the repo. it's only 64MB. Github's max file size limit is 100MB

**Comment by hpzhao** [comment]
Thanks for the info @AlJohri . I'll upload pretrained models in a few days @mollynatsu

**Comment by hpzhao** [comment]
The pretrained models have uploaded. @mollynatsu

**Comment by mollynatsu** [comment]
Thanks！

**Comment by hpzhao** [comment]
The pretrained models have been uploaded. @mollynatsu

**Comment by rococode** [comment]
Thank you for the pretrained models! It took me 2 days to train one model on Azure so it's very much appreciated 😃
