### ISSUE TITLE
sentence labeling codes

### ISSUE THREAD

**Issue by soupstandstop** [hpzhao/SummaRuNNer#30]
嗨，可以請你把sentence label 代碼放上來嗎，我在對每一句作Label時，速度相當慢，想參考您的作法

**Comment by hpzhao** [comment]
可以描述详细点么，是预测打label？

**Comment by dajuzi123** [comment]
那个句子的label0或1是手工打的吗？有没有程序，刚开始做摘要不太懂

**Comment by hpzhao** [comment]
我用的别人的数据集，主流的做法是用人工摘要进行构造抽取式摘要数据集，论文里有说明 @dajuzi123

**Comment by buster120** [comment]
@soupstandstop 我也需要sentence label的代码，想学习一下您的代码，可以吗
