### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by leetiantian** [hpzhao/SummaRuNNer#32]
您好，我在训练的时候报错：
> Traceback (most recent call last):
  File "main.py", line 62, in <module>
    torch.cuda.set_device(args.device)
  File "/home/minelab/anaconda3/envs/py3/lib/python3.5/site-packages/torch/cuda/__init__.py", line 161, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

pytorch版本是0.1.12，请问有可能是什么原因呢？谢谢

**Comment by hpzhao** [comment]
可能是没有安装对应的CUDA支持 @leetiantian

**Comment by leetiantian** [comment]
我把cudnn从5.1.0升级到6.0.21解决了这个问题
