### ISSUE TITLE
Word2Vec

### ISSUE THREAD

**Issue by begummutlu** [hpzhao/SummaRuNNer#35]
Hello,
First of all, thank you for this sharing. 
This is my first experience with a deep learning applications; sorry for inconvenience. I tried to understand how did you use word embeddings, but I only see that you feed the network by features which corresponds the ids of words in the related sentence (`probs = net(features,doc_lens)`). 
I could not understand, in which point of code the tensor called '`features`' has been transformed to word2vec embeddings. It seems to me that the tensor called '`embed`' has been initialized in a `vocab` object (`vocab = utils.Vocab(embed, word2id)`) but it has not been connected to the rnn's input layer.  Could you help me to clarify how and in which order the word embeddings have been transfered to the model?

**Comment by ygjia** [comment]
Hello,
For the default model "RNN_RNN" in training  process, I think the code will load the embedding file (File Path save in 'args.embedding',  default path is 'data/embedding.npz') in this line, 
https://github.com/hpzhao/SummaRuNNer/blob/47de2c0cc81f0464490ec43a7504e6d3075a2742/main.py#L90
then, the code will build the "RNN_RNN" model
https://github.com/hpzhao/SummaRuNNer/blob/47de2c0cc81f0464490ec43a7504e6d3075a2742/main.py#L107-L108
then, the embedding will copy to 'self.embed' in  this line.
https://github.com/hpzhao/SummaRuNNer/blob/47de2c0cc81f0464490ec43a7504e6d3075a2742/models/RNN_RNN.py#L22-L23

**Comment by begummutlu** [comment]
Yes, that's right. The third step you mentioned above was exactly what I am missing. Thanks.
