### ISSUE TITLE
Using pretrained models error : dimension specified as 0 but tensor has no dimensions

### ISSUE THREAD

**Issue by hoinx-0899** [hpzhao/SummaRuNNer#36]
Runtime error.
<img width="1222" alt="Screen Shot 2019-08-12 at 12 41 05 PM" src="https://user-images.githubusercontent.com/51468282/62847080-7d374500-bcfe-11e9-9472-88d8cf25b519.png">

**Comment by hpzhao** [comment]
It's caused by the pytorch version. Use 0.3.1 or adapt the code for the new version @hoinx-0899
