### ISSUE TITLE
System does not summarize (the output document is the same that original document) 

### ISSUE THREAD

**Issue by willian-moura** [hpzhao/SummaRuNNer#37]
Hi @hpzhao , I tried run the system with your pretrained models, and apparently everything works well. But, when I analyzed the output documents (generated by test mode), I noticed that they are the same the original documents. I tried run the predict mode too, with a single document as input (the first example from test dataset) and I had the same result. Do you know what I'm doing wrong? Maybe you already seen a similar bug and know something I can do. Thank you for your time.

Ps: no errors are shown in the terminal

**Comment by hpzhao** [comment]
I'm not sure if it is caused by pytorch version. Pls try the same config. By the way, which pretrained model do you use. If you get the same result, pls tell me. I'll try to figure out what's wrong next week when I'm free. @mrlactobacilo

**Comment by hpzhao** [comment]
I'm not sure if it is caused by pytorch version. Pls try the same config.
By the way, which pretrained model do you use. If you get the same result,
pls tell me. I'll try to figure out what's wrong next week when I'm free.

Willian Moura <notifications@github.com> 于2019年9月22日周日 上午7:15写道：

**Comment by willian-moura** [comment]
I verified my pytorch version, and it is the same you recommend (0.3.1). I'm not using a GPU, maybe this be the problem? By the way I trying with the RNN_RNN and CNN_RNN models, and both don't return a summarized document. I'm gonna debug the test and the predict mode this week to try find what is wrong.

**Comment by willian-moura** [comment]
Hello @hpzhao, sorry, I knows what happening. I'm just analyzing a documents with less then 15 lines, and the topk default is 15, so the documents with less then 15 lines are exactly the same. But the docs with more then 15 lines works. Anyway, very thanks for your attention.

**Comment by garimachhikara128** [comment]
Hi @willian-moura, while using the pre-trained models RNN_RNN and CNN_RNN, I am getting exactly the same summary. Did you also face similar issue ?
