### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by darrayes** [hpzhao/SummaRuNNer#4]
Please provide the format of data or the pickle files. Though it would be better if the data format is explained a bit.

Particularly I am interested in knowing how a complete doc (or a batch of them) is processed first the individual words are processed by the word_gru and then the sentence is processed by sent_gru. How are the weights updated, upon each word or each sentence or complete document. Hence it is necessary to know how the data is fed.

**Comment by hpzhao** [comment]
Hi,  there's Download URL in README file. The data is released in **.pkl**  format. A doc is an instance of class Document which is defined in **helper.py**.
