### ISSUE TITLE
preprocess.py 相关

### ISSUE THREAD

**Issue by gengkai258** [hpzhao/SummaRuNNer#42]
您好，非常感谢您的分享！

我初次接触，最近在看这个preprocess.py文档，请问一下这个py文件是可以生成word2id.json文件的吗？
能否提供一下运行该文件的使用方法呢，以及提到的data/100.w2v的文件可以分享一下吗？

非常感谢！

**Comment by minhtam2048** [comment]
Hi @gengkai258, I found out that you can use another semantic vectors (or word embedding) like Conceptnet numberbatch or GloVe, the code still worked perfectly even when you don't use 100.w2v . But please pay attention to the embedding dimension, the Conceptnet is 300, the GloVe has more versions, depending on which number of dimension you want to use. Remember to change the directory to the located GloVe or Conceptnet file.

**Comment by minhtam2048** [comment]
> 您好，非常感谢您的分享！
> 
> 我初次接触，最近在看这个preprocess.py文档，请问一下这个py文件是可以生成word2id.json文件的吗？
> 能否提供一下运行该文件的使用方法呢，以及提到的data/100.w2v的文件可以分享一下吗？
> 
> 非常感谢！

Hi @gengkai258, I found out that you can use another semantic vectors (also called word embedding) like Conceptnet numberbatch or GloVe, the code still worked perfectly even when you don't use 100.w2v . But please pay attention to the embedding dimension, the Conceptnet is 300, the GloVe has more versions, depending on which number of dimension you want to use. Remember to change the directory to the located GloVe or Conceptnet file.

**Comment by gengkai258** [comment]
> > 您好，非常感谢您的分享！
> > 我初次接触，最近在看这个preprocess.py文档，请问一下这个py文件是可以生成word2id.json文件的吗？
> > 能否提供一下运行该文件的使用方法呢，以及提到的data/100.w2v的文件可以分享一下吗？
> > 非常感谢！
> 
> Hi @gengkai258, I found out that you can use another semantic vectors (also called word embedding) like Conceptnet numberbatch or GloVe, the code still worked perfectly even when you don't use 100.w2v . But please pay attention to the embedding dimension, the Conceptnet is 300, the GloVe has more versions, depending on which number of dimension you want to use. Remember to change the directory to the located GloVe or Conceptnet file.

Thank you so much for your sincerely reply! I have learned a lot~

**Comment by minhtam2048** [comment]
> 
> 
> > > 您好，非常感谢您的分享！
> > > 我初次接触，最近在看这个preprocess.py文档，请问一下这个py文件是可以生成word2id.json文件的吗？
> > > 能否提供一下运行该文件的使用方法呢，以及提到的data/100.w2v的文件可以分享一下吗？
> > > 非常感谢！
> > 
> > 
> > Hi @gengkai258, I found out that you can use another semantic vectors (also called word embedding) like Conceptnet numberbatch or GloVe, the code still worked perfectly even when you don't use 100.w2v . But please pay attention to the embedding dimension, the Conceptnet is 300, the GloVe has more versions, depending on which number of dimension you want to use. Remember to change the directory to the located GloVe or Conceptnet file.
> 
> Thank you so much for your sincerely reply! I have learned a lot~

you are welcome
