### ISSUE TITLE
scripts to produce pkl files?

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#8]
hi @hpzhao, if you get a chance, could you include some of the scripts you ran to generate the pkl files? the google drive link you provided is very helpful but it would be great to have the scripts too for the sake of completeness. it would also make it easy to rerun on a new dataset

**Comment by hpzhao** [comment]
I have just uploaded the script in *src *dir.

2018-01-23 10:45 GMT+08:00 Al Johri <notifications@github.com>:

**Comment by AlJohri** [comment]
great! do you have a script to produce the embedding too? I was wondering if you started from Google News and then modified based on CNN/Daily Mail or trained the embeddings on CNN/Daily Mail alone.

**Comment by hpzhao** [comment]
Sorry for my late answer! I  got embeddings only utilizing the CNN/Daily
Mail alone by word2vec.


Best.

2018-01-24 0:26 GMT+08:00 Al Johri <notifications@github.com>:

**Comment by AlJohri** [comment]
thanks @hpzhao! have you tried using https://github.com/pytorch/text?

**Comment by hpzhao** [comment]
Not yet
